// SMD_Import
// Initial code generated by Softimage SDK Wizard
// Executed Mon Jul 15 00:02:07 UTC+0200 2013 by Mike
// 
// Tip: To add a command to this plug-in, right-click in the 
// script editor and choose Tools > Add Command.

var sPath = InstallationPath(siUserPath) + "\\Addons\\SMD_Tools\\Application\\Plugins\\";

function XSILoadPlugin( in_reg )
{
	in_reg.Author = "Miguel Melara";
	in_reg.Name = "SMD Tools";
	in_reg.Email = "https://twitter.com/neodos_";
	in_reg.URL = "";
	in_reg.Major = 1;
	in_reg.Minor = 0;
	
	in_reg.RegisterEvent("SMD_Import_DragAndDrop",siOnDragAndDrop);
	
	in_reg.RegisterCommand("SMD_Import", "SMD_Import");
	in_reg.RegisterCommand("SMD_Import_Args", "SMD_Import_Args");
	in_reg.RegisterMenu(1003, "SMD_Import_Menu" , false, false);
	
	in_reg.RegisterCommand("SMD_Export", "SMD_Export");
	//in_reg.RegisterCommand("SMD_Import_Args", "SMD_Import_Args");
	in_reg.RegisterMenu(siMenuMainFileExportID, "SMD_Export_Menu" , false, false);
	
	return true;
}

function XSIUnloadPlugin( in_reg )
{
	var strPluginName;
	strPluginName = in_reg.Name;
	Application.LogMessage(strPluginName + " has been unloaded.",siVerbose);
	return true;
}



// SMD file loaded from DragAndDrop event.
function SMD_Import_DragAndDrop_OnEvent( in_ctxt )
{
	action = in_ctxt.GetAttribute("DragAndDropAction");
	source = in_ctxt.GetAttribute("DragSource");
	
	//check if file is an SMD
	if(source.toLowerCase().indexOf(".smd") !== -1)
	{
		in_ctxt.SetAttribute("DragSourceSupported",true);

		if (action == 1)
		{
			import_smd(source, "", "");
		}
	}
	
// 	Return value is ignored as this event can not be aborted.
	return true;
}



function SMD_Import_Init(in_ctxt)
{
	var oCmd;
	oCmd = in_ctxt.Source;
	oCmd.Description = "Import selected SMD.";
	oCmd.ReturnValue = false;
}

function SMD_Import_Args_Init(in_ctxt)
{
	var oCmd;
	oCmd = in_ctxt.Source;
	oCmd.Description = "Import specified SMD with options.";
	oCmd.ReturnValue = false;

	var oArgs;
	oArgs = oCmd.Arguments;
	oArgs.Add("file_path",siArgumentInput,"");
	oArgs.Add("model_name",siArgumentInput,"");
	oArgs.Add("parent",siArgumentInput,"");
}

// SMD import called from dialog
function SMD_Import_Execute(in_ctxt)
{
	var path = select_file("C:\\");
	
	if (path != "")
	{
		import_smd(path, "", "");
	}
}

// Init callback for the menu named "MyCommands_Menu"
function SMD_Import_Menu_Init(in_ctxt)
{
	var oMenu = in_ctxt.Source;
	oMenu.AddSeparatorItem();
    oMenu.AddCommandItem("Import SMD","SMD_Import");
	return true;
}



function select_file(_startdir) 
{
	var path = "";
	var oFileBrowser = XSIUIToolkit.FileBrowser;
	oFileBrowser.DialogTitle = "Select a filename";       // set the title of the file browser
	oFileBrowser.InitialDirectory = _startdir;
	oFileBrowser.Filter = "SMD file (*.smd)|*.smd||" ;  // Allow selection of all files
	oFileBrowser.ShowOpen();                                                  // show an save file dialog
	if (oFileBrowser.FilePathName != "") 
	{
		path = oFileBrowser.FilePathName;
	}
	
	return path;
}

//import SMD with args for model name and parent
function SMD_Import_Args_Execute(file_path, model_name, parent)
{
	import_smd(file_path, model_name, parent);
}

function import_smd(file_path, model_name, parent)
{
	// arguments must be put into a string array
	// yet on the script run, the received argument becomes a string and not the provided an array
	// hence arguments are in a single string split by # char

	var args = [file_path + "#" + model_name + "#" + parent];

	var oProgressBar = XSIUIToolkit.ProgressBar;
	oProgressBar.Maximum = 100;
	oProgressBar.Step = 0;
	oProgressBar.Caption = "SMD Importer: loading " + file_path.replace(/^.*[\\\/]/, '');
	oProgressBar.CancelEnabled = true;
	oProgressBar.Visible = true;
	
	var imported = false;
	
	while(imported == false)
	{
		//oProgressBar.Increment();
		imported = Application.ExecuteScript(sPath + "Import.js", "JScript", "Main", args);
		
		if (oProgressBar.CancelPressed )
		{
			break;
		}		
	}
	
	 //XSIUIToolkit.ProgressBar.Visible = false;
	 oProgressBar.Visible = false;
}

///////////// EXPORT ////////////////////////////////////////////////////////////////////////////////////////////

function SMD_Export_Init(in_ctxt)
{
	var oCmd;
	oCmd = in_ctxt.Source;
	oCmd.Description = "Export the selected Model.";
	oCmd.ReturnValue = false;
}


function SMD_Export_Menu_Init(in_ctxt)
{
	var oMenu = in_ctxt.Source;
	oMenu.AddSeparatorItem();
    oMenu.AddCommandItem("Export SMD","SMD_Export");
	return true;
}


function SMD_Export_Execute(in_ctxt)
{
	var oFileBrowser = XSIUIToolkit.FileBrowser;
	oFileBrowser.DialogTitle = "Select a filename";       // set the title of the file browser
	oFileBrowser.InitialDirectory = Application.ActiveProject2.Path + "\\Models";
	oFileBrowser.Filter = "SMD file (*.smd)|*.smd||" ;  // Allow selection of all files
	oFileBrowser.ShowSave();                                                  // show an save file dialog
	if (oFileBrowser.FilePathName != "") 
	{
		export_smd(oFileBrowser.FilePathName);
	}
}

function export_smd(file_path)
{
	// arguments must be put into a string array
	// yet on the script run, the received argument becomes a string and not the provided an array
	// hence arguments are in a single string split by # char

	var args = [file_path]; //[file_path + "#" + model_name + "#" + parent];
	/*
	var oProgressBar = XSIUIToolkit.ProgressBar;
	oProgressBar.Maximum = 100;
	oProgressBar.Step = 0;
	oProgressBar.Caption = "SMD Exporter: writing " + file_path.replace(/^.*[\\\/]/, '');
	oProgressBar.CancelEnabled = true;
	oProgressBar.Visible = true;
	*/
	var exported = false;
	
	while(exported == false)
	{
		//oProgressBar.Increment();
		exported = Application.ExecuteScript(sPath + "Export.js", "JScript", "Main", args);
		
		/*
		if (oProgressBar.CancelPressed )
		{
			break;
		}		
		*/
	}
	
	 //XSIUIToolkit.ProgressBar.Visible = false;
	 //oProgressBar.Visible = false;
}

